---
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
bracketSameLine: true
arrowParens: 'avoid'
requirePragma: false
insertPragma: false
proseWrap: 'preserve'
