export const assets = [
  'assets/release-notes-1.17.0-beta.1.json',
  'assets/release-notes-1.17.0-beta.0.json',
  'assets/release-notes-1.17.0-alpha.3.json',
  'assets/release-notes-1.17.0-alpha.2.json',
  'assets/release-notes-1.16.2.json',
  'assets/release-notes-1.16.1.json',
  'assets/release-notes-1.16.json',
  'assets/release-notes-1.15.5.json',
  'assets/release-notes-1.15.4.json',
  'assets/release-notes-1.15.3.json',
  'assets/release-notes-1.15.2.json',
  'assets/release-notes-1.15.1.json',
  'assets/release-notes-1.15.json',
];
